export default {
    'hometitle': 'Hello, I am Aaron Chen. Software Engineer in Taiwan',
    'about': 'About',
    'experience' : 'Experience',
    'works':'Works and Projects',
    'email':'Email',
    'resume':'Resume',
    'language':'語言',
    'skills':'Skills',
    'mobiledevelop':'Mobile Development',
    'webdevelop':'Web Development',
    'dasktopdevelop':'Desktop Application Development',
    'database':'Database',
    'developmenttools':'Development Tools',
    'versioncontroltools':'Version Control Tools',
    'abouttitle':'  Hello, I am a software engineer with 8+ years of development experience including DevOps, back-end, web front-end, Windows desktop application. Have experience in back-end refactoring, requirement analysis, keep Code clean and readable and have the best performance, eager to learn and improve my skills.',
    'personaltraits':'Personal Traits',
    'personaltraitslist':'Creative, Insightful, Teamwork, Kind, Brave, Approachable',
    'learntube':'Learning Channels',
    'learntubedescription':'Podcast, Reading, Online Courses, Technical Sharing, Research',

    'neweggtw':'Newegg, Taipei, Taiwan',
    'neweggtwtime':'Sep 2014 - Sep 2018',
    'neweggposition':'Software Engineer',
    'neweggtwdescription':'● Maintain and develop NewEgg.tw website. Include Back end and Front end.',
    'eipdescription':'● Maintain and develop Enterprise Information Portal (EIP). Include Back end and Mobile(Android). Using XMPP, MS SQL Server. And using Active MQ, Solr, Redis made the Back end service response time shorter.',
    'boxdescription':'● Developed the NewEgg Box cloud system desktop application. Using Windows Presentation Foundation (WPF) with MVVM pattern (MVVM Light). Research and share technical skills to improve the team performed.',
   
    'realsun':'RealSun, Taipei, Taiwan',
    'realsuntime':'Mar 2021 - Feb 2022',
    'realsunposition':'System Engineer',
    'realsundescription':'● Maintain and develop Hospital information system (HIS). Using C#, Windows Presentation Foundation (WPF), Entity Framework(DB First), MS SQL, RDLC',
    'yfy':'YFY Inc., Taipei, Taiwan',
    'yfytime':'Apr 2022 - Present',
    'yfyposition':'Second Level Specialist',
    'webdescription':'● Develop internal web applications for the company. Such as Export System, Customs System, Customer Service System, IFRS. Using ASP.NET MVC, .NET(Core), Vue 3, Entity Framework, HTML, JQuery, JavaScript, MS SQL, RDLC',
    'devopsdescription':'● Plan DevOps process. Using Azure DevOps, Jenkins, Git, MS Build, Reporting Services PowerShell, IIS, Kubernetes, Harbor, Notion',

    'npu':'National Penghu University of Science and Technology',
    'activitesandsocieties':'Activities and societies',
    'exchangestudent':'● JiMei University E-commerce department Exchange student',
    'misdegree':'Bachelor\'s degree, Information Management',
    'nputime':'2010 - 2014',
    'finalprojectteamleader':'● Final project team leader',
    'ta':'● Teacher assistant',
    'ciccc':'Cornerstone International Community College of Canada',
    'maintainclassroom':'● Volunteer-Maintain computer classroom',
    'ciccctime':'2019 - 2021',
    'wmap':'Web and Mobile App Development Diploma',
    'education':'Education',
    

    'designedandbuilt':'Designed and Built by Aaron Chen',
    'portfoliousign':'Using React, TypeScript, Bootstrap',
    'simplemusicnotesreaderdescription1':'An Android App for musicians to read music notes. You can open a ',
    'simplemusicnotesreaderdescription2':' file. This app will draw the music notes for you. This app will scroll down automatically. You can set the speed for the scrolling. So you can play and read the notes at the same time.',
    'multiplefilerenamedescription':'A Windows Desktop App. you can rename multiple files. There have three methods for rename. Replace, remove and add characters.',
    'sudokudescription':'A Windows Desktop App. This app can generate random Sudoku question. Have GUI for player play Sudoku. You can choose difficulty. When you finish the sudoku question the timer will stop.',
    'clipboardtranslatordescription':'A Windows Desktop App. This app is a translator. When you copy a vocabulary it will jump a small window at the corner. Which will show you the information and translation about that vocabulary you have copied.',
    'viewgithub':'View GitHub',
    'yrs':'yrs',
    'mos':'mos',
    'ios':'IOS',
    'android':'Android',
    'objectivec':'Objective-C',
    'swift':'Swift',
    'java':'Java',
    'kotlin':'Kotlin',

    'aspnet':'ASP.NET',
    'aspnetmvc':'ASP.NET MVC',
    'aspnetcore':'.NET(Core)',
    'spring':'Spring',
    'vue':'Vue',
    'react':'React',
    'typescript':'TypeScript',
    'javascript':'JavaScript',

    'wpf':'WPF',
    'swing':'Swing',
    'tkinter':'Tkinter',
    'csharp':'C#',
    'python':'Python',

    'mss':'Microsoft SQL Server',
    'mongodb':'MongoDB',
    'firebase':'Firebase',

    'visualstudio':'Visual Studio',
    'vscode':'Visual Studio Code',
    'xcode':'Xcode',
    'androidstudio':'Android Studio',
    'pycharm':'PyCharm',
    'intellij':'IntelliJ',
    
    'git':'Git',
    'tfs':'TFS',

    'devops':'DevOps',
    'azuredevops':'Azure DevOps',
    'jenkins':'Jenkins',
    'harbor':'Harbor',
    'docker':'Docker',
    'kubernetes':'Kubernetes',

    'mvvm':'MVVM',
    '.net':'.NET',
    'rdlc':'RDLC',
    'teamplus':'TeamPlus API',
    'azure':'Azure',
    'yating':'Yating API',
    'openai':'OpenAI API',
    'sms':'SMS API',
    'mailserver':'Mail Server',

    'sudoku':'SUDOKU',
    'clipboardtranslator':'Clipboard Translator',
    'multiplefilerename':'Multiple File Rename',
    'simplemusicnotesreader':'Simple Music Notes Reader',
    'notion':'Notion',

    //'musicreadertech':'Android Kotlin JavaScript MVVM',
    //'multiplefilerenametech':'WPF .NET Framework C# MVVM',
    //'sudokutech':'Swing java',
    //'clipboardtranslatortech':'Swing java'
};