export default {
    'hometitle': 'Hello, I am Aaron Chen. Software Engineer based in Vancouver, BC',
    'about': 'About',
    'experience' : 'Experience',
    'works':'Works',
    'email':'Email',
    'resume':'Resume',
    'language':'語言',
    'skills':'Skills',
    'mobiledevelop':'Mobile Development',
    'webdevelop':'Web Development',
    'dasktopdevelop':'Desktop Application Development',
    'database':'Database',
    'developmenttools':'Development Tools',
    'abouttitle':'  Hello, I am Aaron Chen, a software engineer with 4+ years of experience in Windows desktop application development and 1-year experience in Android development. Have Code refactoring experience. Know how to keep code clean and easy to read also has the best performance. Eager to learn more to continuously improve my skills.',
    'neweggtw':'Newegg, Taipei, Taiwan',
    'neweggtwtime':'Sep 2014 - Sep 2018',
    'neweggposition':'Software Engineer',
    'neweggtwdescription':'● Maintain and develop NewEgg.tw website. Include Back end and Front end.',
    'eipdescription':'● Maintain and develop Enterprise Information Portal (EIP). Include Back end and Mobile(Android). Using XMPP, MS SQL Server. And using Active MQ, Solr, Redis made the Back end service response time shorter.',
    'boxdescription':'● Developed the NewEgg Box cloud system desktop application. Using Windows Presentation Foundation (WPF) with MVVM pattern (MVVM Light). Research and share technical skills to improve the team performed.',
    'designedandbuilt':'Designed and Built by Aaron Chen',
    'portfoliousign':'Using React, TypeScript, Bootstrap',
    'simplemusicnotesreaderdescription1':'An Android App for musicians to read music notes. You can open a ',
    'simplemusicnotesreaderdescription2':' file. This app will draw the music notes for you. This app will scroll down automatically. You can set the speed for the scrolling. So you can play and read the notes at the same time.',
    'multiplefilerenamedescription':'A Windows Desktop App. you can rename multiple files. There have three methods for rename. Replace, remove and add characters.',
    'sudokudescription':'A Windows Desktop App. This app can generate random Sudoku question. Have GUI for player play Sudoku. You can choose difficulty. When you finish the sudoku question the timer will stop.',
    'clipboardtranslatordescription':'A Windows Desktop App. This app is a translator. When you copy a vocabulary it will jump a small window at the corner. Which will show you the information and translation about that vocabulary you have copied.',
    'viewgithub':'View GitHub',
    //Proper nouns 專有名詞 Always English
    'mobileskills':'IOS, Android, Objective-C, Swift, Java, Kotlin',
    'webskills':'ASP.NET, React, TypeScript, JavaScript',
    'desktopskills':'WPF, Swing, Tkinter, C#, Java, Python',
    'databaseskills':'Microsoft SQL Server, MongoDB, Firebase',
    'developtoolskills':'Xcode, Android Studio, Microsoft Visual Studio, Visual Studio Code, PyCharm, IntelliJ, Git',
    'sudoku':'SUDOKU',
    'clipboardtranslator':'Clipboard Translator',
    'multiplefilerename':'Multiple File Rename',
    'simplemusicnotesreader':'Simple Music Notes Reader',
    
    'musicreadertech':'Android Kotlin JavaScript MVVM',
    'multiplefilerenametech':'WPF .NET Framework C# MVVM',
    'sudokutech':'Swing java',
    'clipboardtranslatortech':'Swing java'
};