export default {
    'hometitle': '您好，我是 陳志嶄，一位來自台灣的軟體工程師。',
    'about': '關於',
    'experience' : '經驗',
    'works':'作品與專案',
    'email':'信箱',
    'resume':'履歷',
    'language':'Language',
    'skills':'技能',
    'mobiledevelop':'手機軟體開發',
    'webdevelop':'網頁開發',
    'dasktopdevelop':'桌面程式開發',
    'database':'資料庫',
    'developmenttools':'開發工具',
    'versioncontroltools':'版控工具',
    'abouttitle':'  擁有',
    'abouttitle1':'  年軟體開發經驗，涵蓋 DevOps、後端、網頁前端與 Windows 桌面應用開發。具備後端重構與需求分析能力，重視程式碼的可讀性與效能。熱愛學習與自我成長，不斷精進技術。',
    'personaltraits':'個人特質',
    'personaltraitslist':'創意創新、洞察力強、團隊合作佳、個性善良勇敢、平易近人',
    'learntube':'能力提升學習管道',
    'learntubedescription':'線上課程, 技術分享, 研究',
    'podcast':'Podcast',
    'reading':'閱讀',

    'neweggtw':'台灣新蛋, 台灣, 台北',
    'neweggtwtime':'2014年9月 - 2018年9月',
    'neweggposition':'軟體工程師',
    'neweggtwdescription':'● 維護與開發NewEgg.tw網站，包括前端與後端',
    'eipdescription':'● 維護與開發企業入口網站(EIP)，包括後端與手機端(Android)使用 XMPP、MS SQL Server，使用Active MQ、Solr、Redis提升後端服務回應時間',
    'boxdescription':'● 開發NewEgg Box 雲端系統桌面應用程式，使用Windows Presentation Foundation (WPF) 與 MVVM (MVVM Light)架構。研究與技術分享使團隊有更好的產出',
    
    'realsun':'耀聖資訊, 台灣, 台北',
    'realsuntime':'2021年3月 - 2022年2月',
    'realsunposition':'系統工程師',
    'realsundescription':'● 維護與開發醫療相關桌面應用程式，使用C#、Windows Presentation Foundation (WPF)、Entity Framework(DB First)、MS SQL、RDLC',
    'yfy':'永豐餘投資控股股份有限公司, 台灣, 台北',
    'yfytime':'2022年4月 - 至今',
    'yfyposition':'二級專員',
    'webdescription':'● 開發供公司內部人使用網站 例如：外銷系統、關務系統、客服系統、IFRS，使用ASP.NET MVC、.NET(Core)、Vue 3、Entity Framework、HTML、JQuery、JavaScript、MS SQL、RDLC',
    'devopsdescription':'● 規劃DevOps流程使用Azure DevOps、Jenkins、Git、MSBuild、Reporting Services PowerShell、IIS、Kubernetes、Harbor、Notion',

    'npu':'國立澎湖科技大學',
    'activitesandsocieties':'活動與社團',
    'exchangestudent':'● 曾至廈門集美大學電商管理系交換一學期',
    'misdegree':'資訊管理學學士',
    'nputime':'2010 - 2014',
    'finalprojectteamleader':'● 畢業專題小組組長',
    'ta':'● 助教',
    'ciccc':'Cornerstone International Community College of Canada',
    'maintainclassroom':'● 志工工作 維護電腦教室',
    'ciccctime':'2019 - 2021',
    'wmap':'Web 與 App 開發 非學位課程',
    'education':'學歷',
    'designedandbuilt':'此履歷由陳志嶄設計與製作',
    'portfoliousign':'使用 React, TypeScript, Bootstrap',
    'simplemusicnotesreaderdescription1':'一個給音樂家讀樂譜的Android App，可開啟 ',
    'simplemusicnotesreaderdescription2':' 樂譜檔並顯示內容，並支援自動向下捲動功能，使用者可自訂捲動速度以配合演奏。',
    'multiplefilerenamedescription':'一個你可以批次幫檔案改名的 Windows 桌面軟體，一共有三種改名方法，取代，刪除與新增字元。',
    'sudokudescription':'一個能隨機產生數獨問題的 Windows 桌面軟體，有使用者介面可使使用者玩數獨，可選擇難度，當你完成時計時器會自動暫停。',
    'clipboardtranslatordescription':'一個翻譯的 Windows 桌面軟體，當你複製一個單字時會在角落跳出一個小視窗，上面會顯示關於這個單字的相關資訊與翻譯。',
    'chpiscss':'客服系統',
    'chpiscssd':'管理客服專案，管理處理事項相關文件等，連接Team+處理客服專案',
    'hcisipcs':'關務系統',
    'hcisipcsd':'處理進口相關業務與統計報表',
    'hcismaia':'智能會議助理',
    'hcismaiad':'使用雅婷語音轉文字服務與OpenAI，將會議內容逐字稿轉成謫要',
    'yating':'雅婷',
    'hcismaiad2':'語音轉文字服務與OpenAI，將會議內容逐字稿轉成謫要',
    'hcisens':'緊急重大事件通報',
    'hcisensd':'供廠內人員通報緊急重大事件，並傳簡訊、Email通報給相關人士',
    'hcisifrs':'IFRS集團合併報表系統',
    'hcisifrsd':'將集團內子公司財務報表依International Financial Reporting Standards (國際財務報導準則)合併',
    'hcisoha':'永豐餘百年慶',
    'hcisohad':'協助永豐餘百年慶活動IT系統使用者疑問與故障排除，處理特殊需求',
    
    'viewgithub':'查看 GitHub',
    'yrs':'年',
    'mos':'個月',
    //Proper nouns 專有名詞 Always English
    'ios':'IOS',
    'android':'Android',
    'objectivec':'Objective-C',
    'swift':'Swift',
    'java':'Java',
    'kotlin':'Kotlin',
    'aspnet':'ASP.NET',
    'aspnetmvc':'ASP.NET MVC',
    'aspnetcore':'.NET(Core)',
    'spring':'Spring',
    'vue':'Vue',
    'react':'React',
    'typescript':'TypeScript',
    'javascript':'JavaScript',

    'wpf':'WPF',
    'swing':'Swing',
    'tkinter':'Tkinter',
    'csharp':'C#',
    'python':'Python',

    'mss':'Microsoft SQL Server',
    'mongodb':'MongoDB',
    'firebase':'Firebase',

    'visualstudio':'Visual Studio',
    'vscode':'Visual Studio Code',
    'xcode':'Xcode',
    'androidstudio':'Android Studio',
    'pycharm':'PyCharm',
    'intellij':'IntelliJ',
    
    'git':'Git',
    'tfs':'TFS',

    'devops':'DevOps',
    'azuredevops':'Azure DevOps',
    'jenkins':'Jenkins',
    'harbor':'Harbor',
    'docker':'Docker',
    'kubernetes':'Kubernetes',

    'mvvm':'MVVM',
    '.net':'.NET',
    'rdlc':'RDLC',
    'teamplus':'TeamPlus API',
    'azure':'Azure',
    'yatingapi':'Yating API',
    'openai':'OpenAI API',
    'sms':'SMS API',
    'mailserver':'SMTP',

    'notion':'Notion',
    'sudoku':'SUDOKU',
    'clipboardtranslator':'Clipboard Translator',
    'multiplefilerename':'Multiple File Rename',
    'simplemusicnotesreader':'Simple Music Notes Reader',
};